"""Prepare the independently deployed silent-match function package.

Catalyst deploys each function directory as its own Python bundle. The
silent-match API reuses the crime-query domain modules, so the predeploy hook
vendors the small, explicit dependency closure into a generated directory.
Source remains owned by ``crime_query``; generated files are ignored and
reproducible.
"""
import argparse
import shutil
from pathlib import Path


SHARED_MODULES = (
    "access.py",
    "auth.py",
    "catalog.py",
    "db.py",
    "graph.py",
    "graph_projection.py",
    "mo_embeddings.py",
    "mo_index.py",
    "mo_matcher.py",
    "mo_models.py",
    "mo_normalize.py",
    "rbac.py",
    "silent_match_api.py",
    "silent_match_models.py",
    "silent_match_repository.py",
    "silent_match_scanner.py",
    "silent_match_scoring.py",
    "validate.py",
)


def prepare(root, destination=None):
    """Copy the reviewed shared-module closure into a function directory."""
    root = Path(root)
    source = root / "functions/crime_query"
    target = Path(destination) if destination is not None else root / "functions/silent_match"
    vendor = target / "_vendor"
    vendor.mkdir(parents=True, exist_ok=True)
    for name in SHARED_MODULES:
        source_path = source / name
        if not source_path.is_file():
            raise FileNotFoundError("shared Catalyst module is missing: {}".format(name))
        shutil.copy2(source_path, vendor / name)
    (vendor / ".ksp-vendored").write_text(
        "Generated by tools.prepare_catalyst_deploy; do not edit.\n",
        encoding="utf-8",
    )
    return {"destination": str(vendor), "modules": SHARED_MODULES}


def main(argv=None):
    parser = argparse.ArgumentParser(description="Prepare Catalyst function dependencies")
    parser.add_argument("--root", default=Path(__file__).resolve().parents[1])
    args = parser.parse_args(argv)
    result = prepare(args.root)
    print("Prepared silent_match vendor bundle ({} modules).".format(len(result["modules"])))
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
